# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Log4Mike 
email: blog@vanvendeloo.net 
description: > # this means to ignore newlines until "baseurl:"
Mike sharing his experiences in software development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mike.vanvendeloo.net" # the base hostname & protocol for your site
twitter_username: mikevanvendeloo 
github_username:  mikevanvendeloo 

# Build settings
markdown: kramdown
